### PR TITLE
changed alignment in signup page #10

### PR DESCRIPTION
**Pull request by Ankitasen21**

### CODE REVIEW

**Comment by rajdip-b** [comment]
@Ankitasen21 can you provide screen shot of what you did?

**Review by rajdip-b — CHANGES_REQUESTED** [review]
Can you let the code be as it was earlier and do the following things? 
- in button element, use items between instead of items center
- modify the value of pc to adjust the alignment as mentioned

**Comment by Ankitasen21** [comment]
> @Ankitasen21 can you provide screen shot of what you did?

image

**Comment by Ankitasen21** [comment]
> Can you let the code be as it was earlier and do the following things?
> 
> * in button element, use items between instead of items center
> * modify the value of pc to adjust the alignment as mentioned

I have rolled back the unnecessary changes

**Comment by rajdip-b** [comment]
> > @Ankitasen21 can you provide screen shot of what you did?
> 
> image

A few more improvements still needs to be made
- [ ] Left align the text while maintaining the gap between the text and the icon
- [ ] Reduce the gap by a small percentage
- [ ] Check if the component is responsive in all three(large. medium and small) screen sizes.
Make these changes and we are good to go.

**Pull request closed without merging**
