### PR TITLE
fixed_button_issue

### PR DESCRIPTION
**Pull request by abhrajitray77**

### CODE REVIEW

**Comment by rajdip-b** [comment]
@abhrajitray77 update the function to use `useCallback()` and navigate to `const navigate = useNavigate()`. Then it would be good.

**Comment by abhrajitray77** [comment]
@rajdip-b  Made the new changes. Is this better?
Screenshot from 2022-08-13 12-12-16

**Comment by rajdip-b** [comment]
One last change, remove the `path` variable and inline the code in callback as `navigate(`/codes`)`. Also, remove path from callback dependency :)

**Comment by abhrajitray77** [comment]
Is this correct? I've pushed the changes.
Screenshot from 2022-08-13 12-19-07

**Review by rajdip-b — APPROVED** [review]
Cool! Seems all good to me.

**Comment by abhrajitray77** [comment]
Thanks. I'm a beginner and learnt a lot from this.

**Comment by rajdip-b** [comment]
> Thanks. I'm a beginner and learnt a lot from this.

Everyone starts somewhere and opensource is the greatest learning space you can start from. Congrats on your PR ill merge it shortly :)

**Pull request merged**
